# Generated by Django 4.2.11 on 2024-05-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diabetes',
            field=models.TextField(default='false', verbose_name='糖尿病'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pregnancy',
            field=models.TextField(default='true', verbose_name='怀孕'),
        ),
    ]
