# Generated by Django 4.2.11 on 2024-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_recipefood_amount_remove_recipefood_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-fdc_id'], 'verbose_name': '食品', 'verbose_name_plural': '食品'},
        ),
        migrations.AddField(
            model_name='recipefood',
            name='amount',
            field=models.FloatField(default=0, verbose_name='食品数量'),
        ),
    ]
