# Generated by Django 4.2.11 on 2024-05-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_user_diabetes_alter_user_pregnancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipefood',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='unit',
        ),
    ]
