# Generated by Django 5.0.4 on 2024-05-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_options_recipefood_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-fdc_id'], 'verbose_name': 'food', 'verbose_name_plural': 'food'},
        ),
        migrations.AlterModelOptions(
            name='foodattribute',
            options={'verbose_name': 'food_attribute', 'verbose_name_plural': 'food_attribute'},
        ),
        migrations.AlterModelOptions(
            name='foodattributetype',
            options={'verbose_name': 'food_attribute_type', 'verbose_name_plural': 'food_attribute_type'},
        ),
        migrations.AlterModelOptions(
            name='foodcalorieconversionfactor',
            options={'verbose_name': 'food_calorie_conversion_factor', 'verbose_name_plural': 'food_calorie_conversion_factor'},
        ),
        migrations.AlterModelOptions(
            name='foodcomponent',
            options={'ordering': ['id'], 'verbose_name': 'food_component', 'verbose_name_plural': 'food_component'},
        ),
        migrations.AlterModelOptions(
            name='foodnutrient',
            options={'ordering': ['fdc_id'], 'verbose_name': 'food_nutrient', 'verbose_name_plural': 'food_nutrient'},
        ),
        migrations.AlterModelOptions(
            name='nutrient',
            options={'ordering': ['id'], 'verbose_name': 'nutrient', 'verbose_name_plural': 'nutrient'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'recipe', 'verbose_name_plural': 'recipe'},
        ),
        migrations.AlterModelOptions(
            name='recipefood',
            options={'verbose_name': 'recipe_food', 'verbose_name_plural': 'recipe_food'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.TextField(verbose_name='data_type'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=64, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fdc_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='fdc_id'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_category_id',
            field=models.IntegerField(verbose_name='food_category_id'),
        ),
        migrations.AlterField(
            model_name='food',
            name='publication_date',
            field=models.TextField(verbose_name='publication_date'),
        ),
        migrations.AlterField(
            model_name='foodattribute',
            name='food_attribute_type_id',
            field=models.IntegerField(verbose_name='food_attribute_type_id'),
        ),
        migrations.AlterField(
            model_name='foodattribute',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='foodattribute',
            name='seq_num',
            field=models.IntegerField(verbose_name='seq_num'),
        ),
        migrations.AlterField(
            model_name='foodattribute',
            name='value',
            field=models.TextField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='foodattributetype',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='foodattributetype',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='foodcalorieconversionfactor',
            name='carbohydrate_value',
            field=models.FloatField(verbose_name='carbohydrate_value'),
        ),
        migrations.AlterField(
            model_name='foodcalorieconversionfactor',
            name='fat_value',
            field=models.FloatField(verbose_name='fat_value'),
        ),
        migrations.AlterField(
            model_name='foodcalorieconversionfactor',
            name='protein_value',
            field=models.FloatField(verbose_name='protein_value'),
        ),
        migrations.AlterField(
            model_name='foodcomponent',
            name='data_points',
            field=models.IntegerField(verbose_name='data_points'),
        ),
        migrations.AlterField(
            model_name='foodcomponent',
            name='gram_weight',
            field=models.FloatField(verbose_name='gram_weight'),
        ),
        migrations.AlterField(
            model_name='foodcomponent',
            name='is_refuse',
            field=models.BooleanField(verbose_name='is_refuse'),
        ),
        migrations.AlterField(
            model_name='foodcomponent',
            name='min_year_acquired',
            field=models.IntegerField(verbose_name='min_year_acquired'),
        ),
        migrations.AlterField(
            model_name='foodcomponent',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='foodcomponent',
            name='pct_weight',
            field=models.FloatField(verbose_name='pct_weight'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='amount',
            field=models.FloatField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='data_points',
            field=models.IntegerField(verbose_name='data_points'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='derivation_id',
            field=models.IntegerField(verbose_name='derivation_id'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='fdc_id',
            field=models.IntegerField(verbose_name='food id'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='footnote',
            field=models.TextField(verbose_name='footnote'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='max',
            field=models.FloatField(verbose_name='max'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='median',
            field=models.FloatField(verbose_name='median'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='min',
            field=models.FloatField(verbose_name='min'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='min_year_acquired',
            field=models.IntegerField(verbose_name='min_year_acquired'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='nutrient_id',
            field=models.IntegerField(verbose_name='nutrient_id'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='nutrient_nbr',
            field=models.FloatField(verbose_name='nutrient_nbr'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='rank',
            field=models.IntegerField(verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='unit_name',
            field=models.TextField(verbose_name='unit_name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.TextField(verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='recipe id'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=20, verbose_name='recipe name'),
        ),
        migrations.AlterField(
            model_name='recipefood',
            name='amount',
            field=models.FloatField(default=0, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='recipefood',
            name='food_id',
            field=models.IntegerField(verbose_name='food_id'),
        ),
        migrations.AlterField(
            model_name='recipefood',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='recipefood',
            name='recipe_id',
            field=models.IntegerField(verbose_name='recipe_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_pressure',
            field=models.CharField(default='120/80', max_length=20, verbose_name='BP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diabetes',
            field=models.TextField(default='false', verbose_name='diabetes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(default=170, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='user/default.jpg', upload_to='user/', verbose_name='imge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pregnancy',
            field=models.TextField(default='true', verbose_name='pregnant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default='M', max_length=10, verbose_name='M/F'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=60, verbose_name='Weight'),
        ),
    ]
